### ISSUE TITLE
User Friendly Control Center

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/control-center#1046]
Due to the fact that CC has many functions and that most of the users will be using Control Center for the first time, there are lots of messages, tooltips, and hints necessary to include. Because if a user gets confused trying the product out, most probably he/she would not even download it again. 

All the suggestions and ideas will be put into this epic issue and listed below. The issues will be as much in detail descriptive as it is possible.

Please, do not hesitate to comment about the way how to improve our Control Center.

**Comment by akarasulu** [comment]
People complaining about having proper feedback not knowing when the peer building is done and shit. 

You can give a progress bar to inform the user about how far the peer is in building. This can be done easily by using some events logged by the vagrant boxes which can be used by the vagrant plugin and exposed to CC. The provisioning scripts can push text events to a file. This can be picked up by the plugin and made available to CC.

If y'all need a solid architecture for that call me. Also you can enable a tty console on the VM and just read the output of it like from a serial device.

**Comment by amangeldizhusubaliev** [comment]
Tooltips in peers menu. I think that it will be much better if you do the following:
1) Change disk size tooltip from `Disk size in GB of the Peer` to `Disk size of the Peer in GB` in order to make the format of this message be the same as the format of ram size tooltip:

**Comment by Erkin97** [comment]
I'm thinking about making checking all machine configuration when you press create peer
and add progress bar of this checking

* CC checks vagrant plugins for update
* CC checks vb and vagrant state
* CC checks file directory 
* CC checks available ram and disk size

All this steps should be represented in progress bar

**Comment by amangeldizhusubaliev** [comment]
Tooltips in peers menu. I think that it will be much better if you do the following:
1) Change disk size tooltip from `Disk size in GB of the Peer` to `Disk size of the Peer in GB` in order to make the format of this message be the same as the format of ram size tooltip:
![disk_size](https://user-images.githubusercontent.com/38368928/40700712-7fced226-63fc-11e8-9525-7f1e6a862ff9.png)
![ram_size](https://user-images.githubusercontent.com/38368928/40700711-7fa8bbb8-63fc-11e8-95e0-0d3fae96eb52.png)

2) In 'State' field, change `To stop this Peer, you can run 'stop' to shut it down` to `To stop this Peer, you can run 'stop'` or `You can run 'stop' to shut this Peer down`, to avoid tautology.
![peer_is_running](https://user-images.githubusercontent.com/38368928/40700762-c9c6986e-63fc-11e8-8fb0-00289ab35b8d.png)

3) Change tooltip for CPU field, it should be something like `Number of CPU cores of the Peer`:
![cpu_num](https://user-images.githubusercontent.com/38368928/40700903-72a4e896-63fd-11e8-9737-0750aa4fbb5e.png)

4) Change 'Peer is not ready' tooltip. In my opinion it will be more user-friendly if it will show something like `The Peer is not ready. It means that Peer management is loading and is not accessible right now. Please wait. You can run 'Reload' to reload this Peer.`
![not_ready](https://user-images.githubusercontent.com/38368928/40701165-b56d96d6-63fe-11e8-94f9-c305397cd901.png)

**Comment by Erkin97** [comment]
@amangeldizhusubaliev I have corrected this tooltips, can you see them after update?

**Comment by amangeldizhusubaliev** [comment]
@Erkin97, yes, but not all of the changes.

**Comment by Almansherov** [comment]
Discussion is closed.
