### ISSUE TITLE
VMware Workstation installation on Linux

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/control-center#1444]
More information about VMware Workstation:
https://www.vmware.com/products/workstation-pro/workstation-pro-evaluation.html

**Comment by kurmanbekova6** [comment]
Switched to VMware Workstation provider (CC=>Settings)
Installed needed components (CC)
Installed VMWare  Workstation
Installed Vagrant VMWare Desktop
Installed Vagrant -VMWare-workstation-licence
Installed Vagrant VMWare Utility
Brought peer up
Switched between providers
Tried it several times
Fixed in Master

**Comment by amangeldizhusubaliev** [comment]
It takes ~2-3 minutes to install.

**Comment by kurmanbekova6** [comment]
Checked by test case above. Fixed in Master.

**Comment by Almansherov** [comment]
Tested on Debian and ubuntu according to the testcase above
fixed in prod
