### ISSUE TITLE
Users should be able to delete their SSH key(s) from the list.

### ISSUE THREAD

**Issue by Shahrizada** [subutai-io/control-center#1446]
Right now to delete any SSH key(s) from the list of SSH key management user has to run this command: `rm ~/.ssh/key_name*`
As a user, I wanna be able to delete key(s) with the button click.
`delete` or `-` buttons can be placed on the opposite of each key. 
![screen shot 2018-07-24 at 12 11 21](https://user-images.githubusercontent.com/31571523/43120060-b4f0b14a-8f3a-11e8-8789-e3a61e38647f.png)

**Comment by ibragim13kz** [comment]
Fixed in Master.

**Comment by alinas2403** [comment]
![screenshot from 2018-08-17 11-13-04](https://user-images.githubusercontent.com/42266015/44248914-1b3d2000-a20f-11e8-8f84-1eea664aa723.png)
Changes have been already done

**Comment by ux-scott** [comment]
I saw that. Looks good, I think it's a straightforward solution. Two minor improvements:

1. Make the buttons a little bit bigger, so there is more padding either side of the text (maybe another 10-20 px). Right now it's too crowded.

2. The Remove Key button should only be active when a key is selected. If no key is selected, it should be disabled, with grey text not black. (Don't make it such a light grey that it cannot easily be read by the user, though.) If the button is active when no key is selected from the list, what happens when you click it? Nothing should happen, so better to disable the button.

**Comment by Almansherov** [comment]
Tested the fix on Debian, Windows, MacOS, and Ubuntu.

Fixed in prod

<img width="669" alt="screen shot 2018-10-31 at 11 28 05 am" src="https://user-images.githubusercontent.com/32430693/47767969-3a245c00-dd00-11e8-8784-a1e2467dc2c0.png">
