### ISSUE TITLE
Capitalization issues throughout Control Center 

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/control-center#1569]
The letters and text messages should have Capitalization Standards in every window of CC 
@ux-scott please advice.

**Comment by ux-scott** [comment]
Here's the example from the CC menu:

<img width="219" alt="screen shot 2018-08-15 at 10 00 04 am" src="https://user-images.githubusercontent.com/39801317/44158487-011a0b00-a072-11e8-9e57-e367e5a6a69a.png">

As you can see, for some of the items, both words are capitalized (My Peers, LAN Peers) and in other cases only the first word (Create peer, SSH-keys management, Notifications history). We should be consistent and use title case.* So here, change to Create Peer and Notifications History. 

I'm not sure about SSH keys because I don't know if the hyphen is actually correct there. It could be SSH Keys Management, or SSH-Keys Management. When I go look at the dialog box, it says SSH Key Manager. 

You have the same problem throughout the dialogs, inconsistent capitalization. And a related problem: menu items do not match dialog titles. If the dialog says "SSH Key Manager" then your menu item should be exactly the same. 

Is that clear enough as instructions? I can download CC and flag more examples if you need further help. This isn't a huge usability problem, but rather it doesn't give users a good impression of the software if they notice inconsistent spelling, naming and capitalization - doesn't look professional. 

*Title case is what you generally see in book or article titles. There are many grammatical rules I won't go into, but the short version is, capitalize the main words (nouns, verbs) and pronouns (my, your) but not the little words (the, to, for etc.).

**Comment by ux-scott** [comment]
On the menu, change "SSH-keys management" to "SSH Key Manager" to match the dialog.

**Comment by ux-scott** [comment]
I just had a look at the menu on the master-control-center version:

![screen shot 2018-08-15 at 10 09 44 pm](https://user-images.githubusercontent.com/39801317/44186698-29d4eb80-a0d8-11e8-9193-d3dd01cc33d6.png)

Create Peer looks good. 

Make changes to two others:

SSH-key management  ->  SSH Key Manager
Notifications history  ->  Notification History

For notifications you will also want to change the title of the dialog, so that it also says "Notification History".

**Comment by Almansherov** [comment]
Fixed in master:

![image](https://user-images.githubusercontent.com/32430693/50420882-4e1ba400-07ff-11e9-96c4-6d42075ad353.png)

**Comment by kurmanbekova6** [comment]
![screenshot_23](https://user-images.githubusercontent.com/9501291/50535942-549c7980-0b79-11e9-896d-065577c15860.png)
