### ISSUE TITLE
Layout of the components of CC moved out on Mac

### ISSUE THREAD

**Issue by kurmanbekova6** [subutai-io/control-center#1589]
Layout of the components moved out on Mac
![screen shot 2018-08-14 at 9 40 37 am](https://user-images.githubusercontent.com/9501291/44202843-f444f800-a101-11e8-8c2a-805b56f7d9bc.png)

**Comment by amangeldizhusubaliev** [comment]
Gaps between names of the components and "info" icons will be fixed. However, we should strongly rework provider/browser changing structures to fix these gaps between the names of the components.  It will be fixed with ui/ux changes.

**Comment by ux-scott** [comment]
I don't want to delay things if you are coming up on release but I have a few minor questions about this dialog. It differs slightly from what I suggested back in June: scroll down to 9.0 at https://w2opu2.axshare.com (password "khan").

My idea (see screenshot below) had been that when a component has been installed and is up to date, most current version, then a check mark appear on the right (instead of an update button if the component is not current). If the user wants to uninstall items, they click on the button and only then does a column of check boxes appear for the user to select components (I didn't actually build this out in Axure). My rationale is that users will rarely want to uninstall things, so we don't need to always show them the checkboxes.

<img width="461" alt="screen shot 2018-08-17 at 10 09 55 am" src="https://user-images.githubusercontent.com/39801317/44277016-91895480-a206-11e8-9fbf-9eb2ffcd8213.png">

**Comment by ux-scott** [comment]
It may not have been clear from the Axure sketch - those checks were meant to be check-mark icons rather than checked check-boxes. It was potentially confusing, sorry. This is a good example of why we need iteration rather than just following a wireframe and going straight to release without having me looking at work in progress.

**Comment by ux-scott** [comment]
One issue with the current design (7.1.5-master) is that you cannot uninstall a component if it needs to be updated. You have to update it first before you can see the checkbox. That is why it is better to have the uninstall control make the checkboxes appear, as I had proposed. If needed I can do a full design of this, with all interactions - just let me know.

**Comment by ux-scott** [comment]
Also I question the wisdom of letting users uninstall Chrome from this screen. If you were not paying attention (or worse, we added a "delete all" type control that checked all checkboxes) you could delete your browser and possibly lose bookmarks, extensions etc. Chrome isn't just some specialized component required for Subutai. If we include it in the list of components then either disable the checkbox for uninstall, or pop a little "are you sure" warning dialog if they have checked it.

**Comment by kurmanbekova6** [comment]
![screen shot 2018-10-04 at 3 05 35 pm](https://user-images.githubusercontent.com/9501291/46464113-6a68f100-c77a-11e8-970d-f9772b4de25e.png)

**Comment by kurmanbekova6** [comment]
Layout fixed on master
<img width="616" alt="screen shot 2018-10-04 at 3 06 26 pm" src="https://user-images.githubusercontent.com/9501291/46464036-2bbd5000-c7e7-11e8-823a-1d0b36f32f05.png">

**Comment by Almansherov** [comment]
All looks good in prod:

<img width="605" alt="screen shot 2018-10-31 at 4 09 52 pm" src="https://user-images.githubusercontent.com/32430693/47784610-4fb17a00-dd30-11e8-8fcf-b3cea9744de7.png">

fixed in prod
