### ISSUE TITLE
[master]Progress bar and notifications are not in sync.

### ISSUE THREAD

**Issue by Shahrizada** [subutai-io/control-center#1649]
I have installed p2p via CC component.
According to the progress bar, the installation was complete. (the progress bar was full)
![screen shot 2018-09-04 at 11 35 39](https://user-images.githubusercontent.com/31571523/45012097-840e0000-b037-11e8-9433-6ddb92234e44.png)

But, I got the notification about p2p being installed later.

![screen shot 2018-09-04 at 11 36 55](https://user-images.githubusercontent.com/31571523/45012125-95570c80-b037-11e8-9517-05f19a508da3.png)

So, as a user it makes me confused to see the full progress bar without any action even for ~1 min

**Comment by amangeldizhusubaliev** [comment]
The progress bar of component shows current state of downloading, if it has reached 100% it means download has been completed. While installing/updating progress bar shows so-called busyindicator animation. Progress bars are thin in macos, that's why it is hard to see that animation. We will display the current state of process whether it is downloading or installing in the label of corresponding component button.

**Comment by kurmanbekova6** [comment]
![screen shot 2018-09-10 at 10 57 44 am](https://user-images.githubusercontent.com/9501291/45277319-0ead8f80-b47c-11e8-80f9-fee1b922592c.png)
![screen shot 2018-09-10 at 10 58 16 am](https://user-images.githubusercontent.com/9501291/45277324-12411680-b47c-11e8-9bf8-01baa0e0337a.png)
Fixed in Master

**Comment by Almansherov** [comment]
Created a peer, registered it to bazaar, and checked the timing of notification:

<img width="726" alt="screen shot 2018-10-31 at 4 32 51 pm" src="https://user-images.githubusercontent.com/32430693/47782534-a6b45080-dd2a-11e8-9153-5ca5833151a4.png">

fixed in prod
