### ISSUE TITLE
Search all peers created by Vagrant 

### ISSUE THREAD

**Issue by jadilet** [subutai-io/control-center#1676]
## Expected Behavior

CC should search all peers created by Vagrant. If user creates peer in different directory which CC used peer standard directory(`~/Subutai-peers/`), CC can't show that peer in `My Peers` menu.

## Current Behavior

CC only search peers in directory `~/Subutai-peers/`
 
## Steps to Reproduce

1. Create peer with Vagrant
2. Let's create directory `mkdir ~/cc_should_find_peer`
3. `cd ~/cc_should_find_peer`
4. `vagrant init subutai/stretch-master`
5. `vagrant up --provider virtualbox`
6. `Check CC is found above peer.`

**Comment by Almansherov** [comment]
Followed the instructions above^
As a result, CC is able to see the VMs out of subutai-peers:

![image](https://user-images.githubusercontent.com/32430693/46400018-36c09500-c6ae-11e8-973c-8afc5548ce63.png)

Implemented on master

**Comment by Almansherov** [comment]
This feature is related to the feature with changing vm storage.
Once the vm storage is changed from settings, all the peers in the machine should be seen in cc. 
I created a new peer on the other directory and cc was able to see it. 
note: cc sees only the peers that uses the same provider that is set in the settings of cc. 
fixed in prod.
