### ISSUE TITLE
Do not close terminal when SSH exits with non-zero exit code (67, 68, 73, 78)

### ISSUE THREAD

**Issue by crioto** [subutai-io/control-center#1855]
User must be able to see output from SSH command if the exit code is one of the following: 
67 | Key exchange failed
68 | Host authentication failed
73 | Host key not verifiable
78 | No more auth methods available

**Comment by jadilet** [comment]
Now CC will not close the SSH terminal.
in order to test this issue, please follow the steps:

1) upload ssh key into an environment on mac to container `A`
2) upload ssh key from another machine as well into the same container `A`
3) ssh into the container from machine 2 and delete the ssh key of mac
4) Change terminal option to iTerm in the setting (on Mac)
5) try to ssh into the container
Expected behavior: iTerm will show a message or will close immediately 
so, the issue belongs to iTerm itself

**Comment by kurmanbekova6** [comment]
Followed the steps described above
Result:
Got a message
<img width="598" alt="screen shot 2019-01-31 at 2 54 52 pm" src="https://user-images.githubusercontent.com/9501291/52104124-247e4580-2613-11e9-9178-2e7c31bff7aa.png">
