### ISSUE TITLE
Can't uninstall  e2e plugin via CC [master]

### ISSUE THREAD

**Issue by kurmanbekova6** [subutai-io/control-center#1889]
Steps to reproduce:
Try to uninstall e2e
https://drive.google.com/open?id=1mmhTRbDHL7eJkyVgZpCV03u0466Bjxxa

**Comment by jadilet** [comment]
Seems you installed the Subutai E2E extension by the Chrome store. You can't uninstall the Subutai E2E extension via the CC. You can only uninstall the Subutai E2E extension by the Chrome browser and if you try to uninstall the Subutai E2E extension via the CC, it shows this message `" Due to the Chrome extension policy Control Center cannot uninstall Subutai E2E extension that has been installed via Chrome Web Store."`.

**Comment by Almansherov** [comment]
Then, this issue is not relevant to cc. Closed
